##export DEBEZIUM_VERSION=2.0
#version: '2'
#services:
#  zookeeper:
#    image: quay.io/debezium/zookeeper:2.0
#    ports:
#     - 2181:2181
#     - 2888:2888
#     - 3888:3888
#  kafka:
#    image: quay.io/debezium/kafka:2.0
#    ports:
#     - 9092:9092
#    links:
#     - zookeeper
#    environment:
#     - ZOOKEEPER_CONNECT=zookeeper:2181
#  db2server:
#    image: debezium/db2-cdc:2.0
#    build:
#      context: C:\debezium\debezium-db2-init\db2server
#    privileged: True
#    ports:
#     - 50000:50000
#    environment:
#     - LICENSE=accept
#     - DBNAME=TESTDB2
#     - DB2INST1_PASSWORD=db2inst1-pwd
#     - NAME=db2inst1
#    volumes:
#    - ./db2data:/database
#  connect:
#    image: debezium/connect-db2:2.0
#    build:
#      context: C:\debezium\debezium-db2-init\db2connect
#      args:
#        DEBEZIUM_VERSION: 2.0
#    ports:
#     - 8083:8083
#    links:
#     - kafka
#     - db2server
#    environment:
#     - BOOTSTRAP_SERVERS=kafka:9092
#     - GROUP_ID=1
#     - CONFIG_STORAGE_TOPIC=my_connect_configs
#     - OFFSET_STORAGE_TOPIC=my_connect_offsets
#     - STATUS_STORAGE_TOPIC=my_connect_statuses