server:
  port: 8081

spring:
  datasource:
    url: jdbc:db2://localhost:50000/testdb1
    username: db2inst1
#    password: db2inst1-pwd
    password: ZGIyaW5zdDEtcHdk
    driver-class-name: com.ibm.db2.jcc.DB2Driver

  user-datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
#    password: root
    password: cm9vdA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    hbm2ddl-auto:
    hbm2ddl-auto-db2:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# to keep the JVM running
camel:
  springboot:
    main-run-controller: true
    routes-include-pattern: routes/routes.xml
  threadpool:
    pool-size: 10
    max-queue-size: 1000
  component:
    properties:
      location: routes/camel.properties


activemq-jds:
  name: activemq-demo
  host: tcp://localhost:61616
  session-cache-size: 500
